import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity({ name: 'songs' })
export class Song {
  data: Array<Buffer> = new Array(100).fill(Buffer.alloc(0));
  @PrimaryColumn({ type: 'text' }) id!: string;

  @Column({ type: 'blob' }) data0!: Buffer;
  @Column({ type: 'blob' }) data1!: Buffer;
  @Column({ type: 'blob' }) data2!: Buffer;
  @Column({ type: 'blob' }) data3!: Buffer;
  @Column({ type: 'blob' }) data4!: Buffer;
  @Column({ type: 'blob' }) data5!: Buffer;
  @Column({ type: 'blob' }) data6!: Buffer;
  @Column({ type: 'blob' }) data7!: Buffer;
  @Column({ type: 'blob' }) data8!: Buffer;
  @Column({ type: 'blob' }) data9!: Buffer;
  // @Column({type: 'blob'}) data10: Buffer;
  // @Column({type: 'blob'}) data11: Buffer;
  // @Column({type: 'blob'}) data12: Buffer;
  // @Column({type: 'blob'}) data13: Buffer;
  // @Column({type: 'blob'}) data14: Buffer;
  // @Column({type: 'blob'}) data15: Buffer;
  // @Column({type: 'blob'}) data16: Buffer;
  // @Column({type: 'blob'}) data17: Buffer;
  // @Column({type: 'blob'}) data18: Buffer;
  // @Column({type: 'blob'}) data19: Buffer;
  // @Column({type: 'blob'}) data20: Buffer;
  // @Column({type: 'blob'}) data21: Buffer;
  // @Column({type: 'blob'}) data22: Buffer;
  // @Column({type: 'blob'}) data23: Buffer;
  // @Column({type: 'blob'}) data24: Buffer;
  // @Column({type: 'blob'}) data25: Buffer;
  // @Column({type: 'blob'}) data26: Buffer;
  // @Column({type: 'blob'}) data27: Buffer;
  // @Column({type: 'blob'}) data28: Buffer;
  // @Column({type: 'blob'}) data29: Buffer;
  // @Column({type: 'blob'}) data30: Buffer;
  // @Column({type: 'blob'}) data31: Buffer;
  // @Column({type: 'blob'}) data32: Buffer;
  // @Column({type: 'blob'}) data33: Buffer;
  // @Column({type: 'blob'}) data34: Buffer;
  // @Column({type: 'blob'}) data35: Buffer;
  // @Column({type: 'blob'}) data36: Buffer;
  // @Column({type: 'blob'}) data37: Buffer;
  // @Column({type: 'blob'}) data38: Buffer;
  // @Column({type: 'blob'}) data39: Buffer;
  // @Column({type: 'blob'}) data40: Buffer;
  // @Column({type: 'blob'}) data41: Buffer;
  // @Column({type: 'blob'}) data42: Buffer;
  // @Column({type: 'blob'}) data43: Buffer;
  // @Column({type: 'blob'}) data44: Buffer;
  // @Column({type: 'blob'}) data45: Buffer;
  // @Column({type: 'blob'}) data46: Buffer;
  // @Column({type: 'blob'}) data47: Buffer;
  // @Column({type: 'blob'}) data48: Buffer;
  // @Column({type: 'blob'}) data49: Buffer;
  // @Column({type: 'blob'}) data50: Buffer;
  // @Column({type: 'blob'}) data51: Buffer;
  // @Column({type: 'blob'}) data52: Buffer;
  // @Column({type: 'blob'}) data53: Buffer;
  // @Column({type: 'blob'}) data54: Buffer;
  // @Column({type: 'blob'}) data55: Buffer;
  // @Column({type: 'blob'}) data56: Buffer;
  // @Column({type: 'blob'}) data57: Buffer;
  // @Column({type: 'blob'}) data58: Buffer;
  // @Column({type: 'blob'}) data59: Buffer;
  // @Column({type: 'blob'}) data60: Buffer;
  // @Column({type: 'blob'}) data61: Buffer;
  // @Column({type: 'blob'}) data62: Buffer;
  // @Column({type: 'blob'}) data63: Buffer;
  // @Column({type: 'blob'}) data64: Buffer;
  // @Column({type: 'blob'}) data65: Buffer;
  // @Column({type: 'blob'}) data66: Buffer;
  // @Column({type: 'blob'}) data67: Buffer;
  // @Column({type: 'blob'}) data68: Buffer;
  // @Column({type: 'blob'}) data69: Buffer;
  // @Column({type: 'blob'}) data70: Buffer;
  // @Column({type: 'blob'}) data71: Buffer;
  // @Column({type: 'blob'}) data72: Buffer;
  // @Column({type: 'blob'}) data73: Buffer;
  // @Column({type: 'blob'}) data74: Buffer;
  // @Column({type: 'blob'}) data75: Buffer;
  // @Column({type: 'blob'}) data76: Buffer;
  // @Column({type: 'blob'}) data77: Buffer;
  // @Column({type: 'blob'}) data78: Buffer;
  // @Column({type: 'blob'}) data79: Buffer;
  // @Column({type: 'blob'}) data80: Buffer;
  // @Column({type: 'blob'}) data81: Buffer;
  // @Column({type: 'blob'}) data82: Buffer;
  // @Column({type: 'blob'}) data83: Buffer;
  // @Column({type: 'blob'}) data84: Buffer;
  // @Column({type: 'blob'}) data85: Buffer;
  // @Column({type: 'blob'}) data86: Buffer;
  // @Column({type: 'blob'}) data87: Buffer;
  // @Column({type: 'blob'}) data88: Buffer;
  // @Column({type: 'blob'}) data89: Buffer;
  // @Column({type: 'blob'}) data90: Buffer;
  // @Column({type: 'blob'}) data91: Buffer;
  // @Column({type: 'blob'}) data92: Buffer;
  // @Column({type: 'blob'}) data93: Buffer;
  // @Column({type: 'blob'}) data94: Buffer;
  // @Column({type: 'blob'}) data95: Buffer;
  // @Column({type: 'blob'}) data96: Buffer;
  // @Column({type: 'blob'}) data97: Buffer;
  // @Column({type: 'blob'}) data98: Buffer;
  // @Column({type: 'blob'}) data99: Buffer;

  fill() {
    this.data0 = this.data[0];
    this.data1 = this.data[1];
    this.data2 = this.data[2];
    this.data3 = this.data[3];
    this.data4 = this.data[4];
    this.data5 = this.data[5];
    this.data6 = this.data[6];
    this.data7 = this.data[7];
    this.data8 = this.data[8];
    this.data9 = this.data[9];
    // this.data10 = this.data[10];
    // this.data11 = this.data[11];
    // this.data12 = this.data[12];
    // this.data13 = this.data[13];
    // this.data14 = this.data[14];
    // this.data15 = this.data[15];
    // this.data16 = this.data[16];
    // this.data17 = this.data[17];
    // this.data18 = this.data[18];
    // this.data19 = this.data[19];
    // this.data20 = this.data[20];
    // this.data21 = this.data[21];
    // this.data22 = this.data[22];
    // this.data23 = this.data[23];
    // this.data24 = this.data[24];
    // this.data25 = this.data[25];
    // this.data26 = this.data[26];
    // this.data27 = this.data[27];
    // this.data28 = this.data[28];
    // this.data29 = this.data[29];
    // this.data30 = this.data[30];
    // this.data31 = this.data[31];
    // this.data32 = this.data[32];
    // this.data33 = this.data[33];
    // this.data34 = this.data[34];
    // this.data35 = this.data[35];
    // this.data36 = this.data[36];
    // this.data37 = this.data[37];
    // this.data38 = this.data[38];
    // this.data39 = this.data[39];
    // this.data40 = this.data[40];
    // this.data41 = this.data[41];
    // this.data42 = this.data[42];
    // this.data43 = this.data[43];
    // this.data44 = this.data[44];
    // this.data45 = this.data[45];
    // this.data46 = this.data[46];
    // this.data47 = this.data[47];
    // this.data48 = this.data[48];
    // this.data49 = this.data[49];
    // this.data50 = this.data[50];
    // this.data51 = this.data[51];
    // this.data52 = this.data[52];
    // this.data53 = this.data[53];
    // this.data54 = this.data[54];
    // this.data55 = this.data[55];
    // this.data56 = this.data[56];
    // this.data57 = this.data[57];
    // this.data58 = this.data[58];
    // this.data59 = this.data[59];
    // this.data60 = this.data[60];
    // this.data61 = this.data[61];
    // this.data62 = this.data[62];
    // this.data63 = this.data[63];
    // this.data64 = this.data[64];
    // this.data65 = this.data[65];
    // this.data66 = this.data[66];
    // this.data67 = this.data[67];
    // this.data68 = this.data[68];
    // this.data69 = this.data[69];
    // this.data70 = this.data[70];
    // this.data71 = this.data[71];
    // this.data72 = this.data[72];
    // this.data73 = this.data[73];
    // this.data74 = this.data[74];
    // this.data75 = this.data[75];
    // this.data76 = this.data[76];
    // this.data77 = this.data[77];
    // this.data78 = this.data[78];
    // this.data79 = this.data[79];
    // this.data80 = this.data[80];
    // this.data81 = this.data[81];
    // this.data82 = this.data[82];
    // this.data83 = this.data[83];
    // this.data84 = this.data[84];
    // this.data85 = this.data[85];
    // this.data86 = this.data[86];
    // this.data87 = this.data[87];
    // this.data88 = this.data[88];
    // this.data89 = this.data[89];
    // this.data90 = this.data[90];
    // this.data91 = this.data[91];
    // this.data92 = this.data[92];
    // this.data93 = this.data[93];
    // this.data94 = this.data[94];
    // this.data95 = this.data[95];
    // this.data96 = this.data[96];
    // this.data97 = this.data[97];
    // this.data98 = this.data[98];
    // this.data99 = this.data[99];
  }
}
